### ISSUE TITLE
Map-to-POI support

### ISSUE THREAD

**Issue by ccprog** [refugeehackathon/refugeetransit-design#1]
This will be the repo for the Drupal stuff, right? @ligi , could you please add me, then? In addition, I need access to migrationmulti.tem.li.

First thing I'd like to look into is how to leverage map display. The idea :
- use the same iconset app-side and web-side
- select a category by icon and pinpoint/geocode a new geolocation and fields for a new POI appear below
- click on a existing pin to edit the related POI

I'll be looking at [Leaflet](https://www.drupal.org/project/leaflet) which might bring the [mapfix](https://github.com/refugeehackathon/mapfix) design in.

**Comment by ligi** [comment]
sounds good - for access to migrationmulti.tem.li you have to ask @t2d - I have no rights there
afaik this repo is only for images and such stuff - not yet sure where the drupal-stuff will go - @johnjohndoe do you know?

**Comment by ligi** [comment]
ah I think the drupal-stuff will go here: https://github.com/refugeehackathon/refugeetransit-website and you already have permissions for this - so I am closing this issue

**Comment by johnjohndoe** [comment]
@ligi @ccprog 

[refugeetransit-website](https://github.com/refugeehackathon/refugeetransit-website) is the repository for the overall project description. This will contain static pages most constructed likely as [GitHub pages](https://pages.github.com/).

The Drupal API can be found in [refugeetransit-api](https://github.com/refugeehackathon/refugeetransit-api). Not sure if this is about the API only or if there is code for a web interface. @ccprog Please talk to the [contributors there](https://github.com/refugeehackathon/refugeetransit-api/graphs/contributors).

@ligi I do not have access to all the repositories. If I would I would update the READMEs to make it clear what all the repositories are created for.

**Comment by ligi** [comment]
you should have access to all repos now
On 26.10.2015 19:21, Tobias Preuss wrote:

> @ligi https://github.com/ligi @ccprog https://github.com/ccprog
> 
> refugeetransit-website
> https://github.com/refugeehackathon/refugeetransit-website is the
> repository for the overall project description. This will contain static
> pages most constructed likely as GitHub pages https://pages.github.com/.
> 
> The Drupal API can be found in refugeetransit-api
> https://github.com/refugeehackathon/refugeetransit-api. Not sure if
> this is about the API only or if there is code for a web interface.
> @ccprog https://github.com/ccprog Please talk to the contributors
> there
> https://github.com/refugeehackathon/refugeetransit-api/graphs/contributors.
> 
> @ligi https://github.com/ligi I do not have access to all the
> repositories. If I would I would update the READMEs to make it clear
> what all the repositories are created for.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/refugeehackathon/refugeetransit-design/issues/1#issuecomment-151236118.

## 

best regards,
ligi
http://ligi.de

**Comment by johnjohndoe** [comment]
@ligi I still cannot add a short description to the top of the page.

**Comment by ligi** [comment]
now?

On 26.10.2015 19:33, Tobias Preuss wrote:

> @ligi https://github.com/ligi I still cannot add a short description
> to the top of the page.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/refugeehackathon/refugeetransit-design/issues/1#issuecomment-151240661.

## 

best regards,
ligi
http://ligi.de

**Comment by ccprog** [comment]
That is how I see it:
- refugeetransit-website: overall description
- refugeetransit-design (?): datainput on migrationmulti.tem.li. There might be config code and theming
- refugeetransit-api: api on migrationapi.tem.li
- migrationapi.tem.li-android: the data presentation

If you see another the role of refugeetransit-design, we'll need (yet) another project...

@t2d: applied for an account on migrationmulti.tem.li

**Comment by ligi** [comment]
IMHO:
- refugeetransit-website: overall description & datainput
- refugeetransit-design: design / images
- refugeetransit-api: api on migrationapi.tem.li
- migrationapi.tem.li-android: mobile app / data presentation

I think we should not open yet another repo

On 26.10.2015 20:10, Claus Colloseus wrote:

> That is how I see it:
> - refugeetransit-website: overall description
> - refugeetransit-design (?): datainput on migrationmulti.tem.li. There
>   might be config code and theming
> - refugeetransit-api: api on migrationapi.tem.li
> - migrationapi.tem.li-android: the data presentation
> 
> If you see another the role of refugeetransit-design, we'll need (yet)
> another project...
> 
> @t2d https://github.com/t2d: applied for an account on
> migrationmulti.tem.li
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/refugeehackathon/refugeetransit-design/issues/1#issuecomment-151253170.

## 

best regards,
ligi
http://ligi.de

**Comment by johnjohndoe** [comment]
@ligi 

> now?

yes. thank you.
